apiVersion: v1
kind: Service
metadata:
  name: voting-web-service
  labels:
    name: voting-web-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
  selector:
    name: voting-app-pod
    app: demo-voting-app 